name: Player-Tracker
main: org.LostTheGame.PlayerTracker.PlayerTracker
author: NINJ4
softdepend: [Essentials, CommandBook, FigAdmin, BanHammer]
version: 1.1.5

commands:
  track:
    description: Shows information about the target player.
    usage: /track [-ia] <player|IP|stats>
    permission: playertracker.track
    permission-message: You don't have permission.
  hidetracks:
    description: Makes a player invisible to tracking.
    usage: /hidetracks <player>
    permission: playertracker.hidetracks
    permission-message: You don't have permission.
  unhidetracks:
    description: Makes a hidden player visible to tracking again.
    usage: /unhidetracks <player>
    permission: playertracker.hidetracks
    permission-message: You don't have permission.
    
permissions:    
    playertracker.*:
        description: Gives access to all Player-Tracker commands
        children:
            playertracker.track: true
            playertracker.onJoin: true
            playertracker.hidetracks: true
            playertracker.hidetracks.override: true
    playertracker.track:
        description: Gives access to track players by name or IP
        default: op
    playertracker.onJoin:
        description: Gives a short report on a player as they join
        default: op
    playertracker.hidetracks:
        description: Can add/remove users to the hidden players list
        default: op
    playertracker.hidetracks.override:
        description: Can lookup/list users even if they are hidden
        default: false
    
